version: "3"
services:
  jupyter:
    image: local-jupyter:latest
    build: ./local-jupyter
    ports:
      - 8888:8888
      - 8000:8000
    networks:
      - pythonista
  mysql:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0p3n5t4ck
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - pythonista
volumes:
  db_data:
networks:
  pythonista: